---

- name: Get skycoin-exchange
  shell: go get github.com/skycoin/skycoin-exchange
  register: result
  failed_when: result.rc > 1

# - name: Sync skycoin-exchange dependencies
#   shell: glock sync github.com/skycoin/skycoin-exchange
