---

- name: Install git
  action: apt pkg=git-core state=installed

- name: Install curl
  action: apt pkg=curl state=installed

- name: Install supervisor
  action: apt pkg=supervisor state=installed

# - name: Get glock
#   shell: go get github.com/robfig/glock
#
# - name: Symlink glock
#   file: src="/usr/go/bin/glock"
#         dest="/usr/local/bin/glock"
#         state=link

- name: Install gox
  shell: go get github.com/mitchellh/gox

- name: Symlink gox
  file: src="/usr/go/bin/gox"
        dest="/usr/local/bin/gox"
        state=link

- name: Create logs directory
  shell: mkdir -p /var/log/supervisor/debian

- name: Copy supervisord config
  copy: src=supervisor/debian.conf dest=/etc/supervisord.conf
